modLoader="javafml"
loaderVersion="[45,)"
license="CC BY-NC-ND 4.0"
issueTrackerURL="https://github.com/HexagonNico/MinecraftMod-ElytraSkins/issues"

[[mods]]
modId="elytras"
version="${file.jarVersion}"
displayName="Elytra Skins"
#updateJSONURL="https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/"
displayURL="https://github.com/HexagonNico/MinecraftMod-ElytraSkins"
logoFile="logo.png"
credits="vanillatweaks.net"
authors="HexagonNico"
description="Adds more elytra skins"

[[dependencies.elytras]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.elytras]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
