modLoader="javafml"
loaderVersion="[47,)"
license="CC BY-NC 4.0"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"
[[mods]]
modId="elytras"
version="${file.jarVersion}"
displayName="Elytra Skins"
#updateJSONURL="https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="logo.png"
credits="vanillatweaks.net"
authors="HexagonNico"
description="Adds more elytra skins"

[[dependencies.elytras]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.elytras]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
